<?php declare(strict_types=1);

namespace Mustache\Contract;

use Mustache\Psr;

/**
 * Mustache Cache interface.
 *
 * Interface for caching and loading \Mustache\Template classes
 * generated by the \Mustache\Compiler.
 */
interface Cache
{
    /**
     * Load a compiled \Mustache\Template class from cache.
     *
     * @param string $key
     *
     * @return bool indicates successfully class load
     */
    public function load(string $key): bool;

    /**
     * Cache and load a compiled \Mustache\Template class.
     *
     * @param string $key
     * @param string $value
     */
    public function cache(string $key, string $value);

    /**
     * Set a logger instance.
     *
     * @param Logger|Psr\Log\LoggerInterface $logger
     */
    public function setLogger($logger = null);
}
